### PR TITLE
Rework series apply

### PR DESCRIPTION
**Pull request by ezequielgarcia**
This pull request is an attempt to improve the user experince by giving some git-am-like output.

Also, the series-apply command is reworked, to make it easier to deal with a conflict when the series cannot be applied cleanly.

### CODE REVIEW

**Comment by stephenfin** [comment]
Thanks for the PR - much appreciated. I'm not sure about this. On one hand, I get the motivation, particularly for larger patch sets where conflicts are likely. On the other hand though, the reason we do this in the first place is to minimise the amount of requests we need to make for larger series (always 1 rather than N). A quick look at the [git-am man page](https://git-scm.com/docs/git-am) suggests there is some conflict resolution tooling available (things like the `--continue` command). Are these not adequate?

Also, there are tests that need to be resolved but we can wait until we decide whether this is necessary or not before doing anything here.

**Comment by ezequielgarcia** [comment]
Hi @stephenfin, thanks for the quick reply. Working with larg-ish (5+ is already large in this context), is the motivation for this, as you say. If there is a conflict, `git-am` simply doesn't apply anything, and then you have to start manually applying individual patches, until you reach the conflict.

How about passing an option to the series-appy command?

Also, what do you think about the second patch, about printing the output? I really like to see the result of git-pw.

PS: git-pw is a great tool, have you considered making it an official tool of git, a-la git-send-email? I don't really know how that works, though.

**Comment by stephenfin** [comment]
> Hi @stephenfin, thanks for the quick reply. Working with larg-ish (5+ is already large in this context), is the motivation for this, as you say. If there is a conflict, `git-am` simply doesn't apply anything, and then you have to start manually applying individual patches, until you reach the conflict.

That's not what I'm seeing. Say I try to apply the [an outdated series](http://patchwork.ozlabs.org/project/patchwork/list/?series=70696) to [Patchwork itself](https://github.com/getpatchwork/patchwork).

```
$ git --version
git version 2.20.1

$ git pw series apply 70696
Applying: fields: Add ColorField
Applying: models: Add submission labels
Applying: parser: Extract and save labels
Applying: parser: Remove matching label from subject prefixes
Applying: admin: Group register calls at bottom
Using index info to reconstruct a base tree...
M       patchwork/admin.py
Falling back to patching base and 3-way merge...
Auto-merging patchwork/admin.py
Applying: admin: Add label views
Using index info to reconstruct a base tree...
M       patchwork/admin.py
Falling back to patching base and 3-way merge...
Auto-merging patchwork/admin.py
CONFLICT (content): Merge conflict in patchwork/admin.py
Resolved 'patchwork/admin.py' using previous resolution.
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0006 admin: Add label views
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

As noted in the last few lines, it successfully applies patches 1-5 and fails on 6. I need to manually resolve those (or not, because I'd previously resolved them and am using [git-rerere](https://git-scm.com/docs/git-rerere)) but, once done, I can use `git am --continue`.

Do you see something different? If so, are you using an older version of `git`, perhaps?

> How about passing an option to the series-appy command?
> 
> Also, what do you think about the second patch, about printing the output? I really like to see the result of git-pw.

Yup, I'm OK with that. Want to propose it in a separate PR to avoid the other patch blocking it?

> PS: git-pw is a great tool, have you considered making it an official tool of git, a-la git-send-email? I don't really know how that works, though.

Eh. This is still specific to a certain tool so I'm not sure if justification could be made for integrating into git core. I'd be more eager to get this packaged for Fedora/Ubuntu/Debian, but I need to find time to do that.

**Comment by ezequielgarcia** [comment]
> > Hi @stephenfin, thanks for the quick reply. Working with larg-ish (5+ is already large in this context), is the motivation for this, as you say. If there is a conflict, `git-am` simply doesn't apply anything, and then you have to start manually applying individual patches, until you reach the conflict.
> 

Sigh, right, I was wrong. This is not the issue I wanted to fix here. See below. 

> That's not what I'm seeing. Say I try to apply the [an outdated series](http://patchwork.ozlabs.org/project/patchwork/list/?series=70696) to [Patchwork itself](https://github.com/getpatchwork/patchwork).
> 
> ```
> $ git --version
> git version 2.20.1
> 
> $ git pw series apply 70696
> Applying: fields: Add ColorField
> Applying: models: Add submission labels
> Applying: parser: Extract and save labels
> Applying: parser: Remove matching label from subject prefixes
> Applying: admin: Group register calls at bottom
> Using index info to reconstruct a base tree...
> M       patchwork/admin.py
> Falling back to patching base and 3-way merge...
> Auto-merging patchwork/admin.py
> Applying: admin: Add label views
> Using index info to reconstruct a base tree...
> M       patchwork/admin.py
> Falling back to patching base and 3-way merge...
> Auto-merging patchwork/admin.py
> CONFLICT (content): Merge conflict in patchwork/admin.py
> Resolved 'patchwork/admin.py' using previous resolution.
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch' to see the failed patch
> Patch failed at 0006 admin: Add label views
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```
> As noted in the last few lines, it successfully applies patches 1-5 and fails on 6. I need to manually resolve those (or not, because I'd previously resolved them and am using [git-rerere](https://git-scm.com/docs/git-rerere)) but, once done, I can use `git am --continue`, which will keep applying patches until all are applied or I hit another conflict.
> 

Right. But how do you fix the conflict now?

The reason I want to download individual patches (even it slightly slower) is because it gives more freedom at conflict-fix time.

You can inspect the patches in the series more easily by having them available as separate mbox files. Not sure this sounds convincing, but it's what fits my worflow better. Having a single mbox file with the entire series isn't really helpful for me.

**Comment by stephenfin** [comment]
> Right. But how do you fix the conflict now?
> 
> The reason I want to download individual patches (even it slightly slower) is because it gives more freedom at conflict-fix time.
> 
> You can inspect the patches in the series more easily by having them available as separate mbox files. Not sure this sounds convincing, but it's what fits my worflow better. Having a single mbox file with the entire series isn't really helpful for me.

Personally, I'd resolve it like any other conflict: `git status` to figure out where the conflicts are then jump into `vim` and edit to my hearts content (I used to use `meld` but it doesn't work when you're connected to a distant machine). That said, I realize that everyone has a [different workflow](https://xkcd.com/1172/) so there could be some value in spitting out multiple patches. If that works for you, I'd be happy to accept but only if it's the non-default behavior (i.e. hide it behind a flag).

The other option you might want to consider is simply splitting the downloaded mbox. That would mean you only need a single request (useful for larger series) and would be easy to do (simply split on every two empty lines of the presence of `From ` lines (without the colon)). I'd probably opt for this because it's going to place less load on the server, fwiw.

**Comment by ezequielgarcia** [comment]
@stephenfin hm, I was too fast on this one. You are right, after a git-am failure, it's perfectly possible to resolve the conflict. I'm closing this.

**Pull request closed without merging**
