### PR TITLE
Dafna 2

### PR DESCRIPTION
**Pull request by kamomil**

### CODE REVIEW

**Comment by stephenfin** [comment]
Thanks! This looks much better. Not sure why CI hasn't kicked off here. I assume it's something to do with travis-ci.org disappearing. I will investigate. In the interim, could you add a simple unit test to verify this functionality. We already have tests for the download to file and download to stdout paths, so we just need one for the download to directory path.

**Review by stephenfin — CHANGES_REQUESTED** [review]
I'd like to see unit tests updated before we merge this. Otherwise, this LGTM

**Comment by kamomil** [comment]
hi, could you instruct me how to run the unti tests?

**Comment by stephenfin** [comment]
Sure. You can run `tox` to run all tests. Run e.g. `tox -e py36` to run a specific environment. If this command isn't available, you can install it from pypi (`pip install tox`) or your distro repos if on Linux (typically `python3-pip`)

**Pull request closed without merging**
